version: "3.8"

services:
  #
  # WebServer Service
  #
  webserver:
    container_name: ${PROJECT}-webserver-${ENVIRONMENT}
    build:
      context: ${PWD}/docker/nginx
      args:
        - FROM_IMAGE=${NGINX_IMAGE_FROM_IMAGE}
        - FROM_TAG=${NGINX_IMAGE_FROM_TAG}
    working_dir: ${WORKING_DIR}
    environment:
      - PHP_IMAGE_EXPOSED_PORT=${PHP_IMAGE_EXPOSED_PORT}
      - WORKING_DIR=${WORKING_DIR}
    volumes:
      - "${PWD}:${WORKING_DIR}"
      - "${PWD}/docker/nginx/files/nginx.conf:/etc/nginx/nginx.conf"
      - "${PWD}/docker/nginx/files/docker-nginx-default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "${HOST_NGINX_PORT}:80"
    networks:
      boilerplate_network:
        aliases:
          - ${PROJECT}_network
        ipv4_address: ${NETWORK_IP_DOMAIN}.1

  php-fpm:
    container_name: ${PROJECT}-php-fpm-${ENVIRONMENT}
    build:
      context: ${PWD}/docker/php-fpm
      args:
        - EXPOSED_PORT=${PHP_IMAGE_EXPOSED_PORT}
        - WORKING_DIR=${WORKING_DIR}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    working_dir: ${WORKING_DIR}
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_IMAGE_TARGET_TAG=${MARIADB_IMAGE_FROM_TAG}
    volumes:
      - "${PWD}:${WORKING_DIR}"
      - "${PWD}/docker/php-fpm/files/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini"
    networks:
      boilerplate_network:
        aliases:
          - ${PROJECT}_network
        ipv4_address: ${NETWORK_IP_DOMAIN}.2

  mariadb:
    container_name: ${PROJECT}-mariadb-${ENVIRONMENT}
    build:
      context: ${PWD}/docker/mariadb
      args:
        - FROM_IMAGE=${MARIADB_IMAGE_FROM_IMAGE}
        - FROM_TAG=${MARIADB_IMAGE_FROM_TAG}
    working_dir: ${WORKING_DIR}
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - "${PWD}/docker/mariadb/data:/var/lib/mysql"
      - "${PWD}/docker/mariadb/files/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "${HOST_MARIADB_PORT}:3306"
    networks:
      boilerplate_network:
        aliases:
          - ${PROJECT}_network
        ipv4_address: ${NETWORK_IP_DOMAIN}.3

  maildev:
    container_name: ${PROJECT}-maildev-${ENVIRONMENT}
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    networks:
      boilerplate_network:
        aliases:
          - ${PROJECT}_network
        ipv4_address: ${NETWORK_IP_DOMAIN}.4

networks:
  boilerplate_network:
    name: ${PROJECT}_network
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_IP_DOMAIN}.0/8
